---
- name: Discover Windows hosts in network
  hosts: localhost
  gather_facts: no
  vars:
    subnet: "172.29.10.0/24"
  tasks:
    - name: Scan subnet for WinRM port (5985)
      community.general.nmap:
        ports: "5985"
        hosts: "{{ subnet }}"
        state: present
      register: scan_result

    - name: Extract available IPs
      set_fact:
        alive_hosts: "{{ scan_result.results | json_query('[?status.state==`open`].host') }}"

    - name: Save dynamic inventory
      copy:
        dest: "./windows_dynamic.ini"
        content: |
          [windows]
          {% for ip in alive_hosts %}
          {{ ip }}
          {% endfor %}
