---
- name: In-place upgrade from Windows 10 to Windows 11
  hosts: all
  gather_facts: no
  tasks:

    - name: Create temp directory
      win_file:
        path: C:\Temp
        state: directory

    - name: Copy ISO from network share to local disk
      win_shell: |
        Copy-Item "\\172.29.10.216\os\Win11_25H2_English_x64.iso" "C:\Temp\Win11.iso" -Force

    - name: Mount local ISO
      win_shell: |
        Mount-DiskImage -ImagePath "C:\Temp\Win11.iso"

    - name: Get mounted ISO drive letter
      win_shell: |
        (Get-DiskImage -ImagePath "C:\Temp\Win11.iso" | Get-Volume).DriveLetter
      register: iso_drive

    - name: Start Windows 11 setup silently
      win_shell: |
        {{ iso_drive.stdout }}:\setup.exe /auto upgrade /quiet /noreboot /compat IgnoreWarning

    - name: Reboot the machine to complete upgrade
      win_reboot:
        msg: "Rebooting to complete Windows 11 upgrade"
        reboot_timeout: 3600
