---
- name: In-place upgrade from Windows 10 to 11
  hosts: all
  gather_facts: no
  tasks:

    - name: Create temp directory
      win_file:
        path: C:\Temp
        state: directory

    - name: Map UNC share (Z:)
      win_shell: |
        $pass = ConvertTo-SecureString "Root@1234" -AsPlainText -Force
        $cred = New-Object System.Management.Automation.PSCredential("Administrator", $pass)
        New-PSDrive -Name Z -PSProvider FileSystem -Root "\\172.29.10.216\os" -Credential $cred -Persist -ErrorAction Stop

    - name: Copy ISO to local
      win_shell: Copy-Item "Z:\Win11_25H2_English_x64.iso" "C:\Temp\Win11.iso" -Force

    - name: Mount ISO
      win_shell: Mount-DiskImage -ImagePath "C:\Temp\Win11.iso"

    - name: Detect drive letter
      win_shell: (Get-DiskImage -ImagePath "C:\Temp\Win11.iso" | Get-Volume).DriveLetter
      register: iso_drive

    - name: Run Windows 11 setup
      win_shell: |
        {{ iso_drive.stdout }}:\setup.exe /auto upgrade /quiet /noreboot /compat IgnoreWarning

    - name: Reboot
      win_reboot:
        reboot_timeout: 3600
