---
- name: In-place upgrade from Windows 11 21H2 to 24H2
  hosts: all
  gather_facts: no
  tasks:

    - name: Mount local ISO
      win_shell: Mount-DiskImage -ImagePath "C:\OS\Win11_25H2_English_x64iso"

    - name: Get mounted ISO drive letter
      win_shell: |
        (Get-DiskImage -ImagePath "C:\OS\Win11_25H2_English_x64" | Get-Volume).DriveLetter
      register: iso_drive

    - name: Start Windows 11 setup silently
      win_shell: |
        {{ iso_drive.stdout }}:\setup.exe /auto upgrade /quiet /noreboot /compat IgnoreWarning

    - name: Reboot to complete upgrade
      win_reboot:
        msg: "Rebooting to complete Windows 11 24H2 upgrade"
        reboot_timeout: 3600
