---
- name: In-place upgrade Windows 11 21H2 → 25H2
  hosts: all
  gather_facts: no

  tasks:

    - name: Ensure OS directory exists
      win_file:
        path: C:\OS
        state: directory

    - name: Check if ISO exists
      win_shell: Test-Path "C:\OS\Win11_25H2_English_x64.iso"
      register: iso_exists
      failed_when: iso_exists.stdout | trim != "True"

    - name: Mount ISO
      win_shell: |
        Mount-DiskImage -ImagePath "C:\OS\Win11_25H2_English_x64.iso"

    - name: Get mounted ISO drive letter
      win_shell: |
        (Get-DiskImage -ImagePath "C:\OS\Win11_25H2_English_x64.iso" | Get-Volume).DriveLetter
      register: iso_drive

    - name: Run Windows 11 setup (silent)
      win_shell: |
        $drive = "{{ iso_drive.stdout | trim }}"
        Start-Process "$drive`:\setup.exe" -ArgumentList "/auto upgrade /quiet /compat IgnoreWarning" -Wait

    - name: Reboot after upgrade
      win_reboot:
        reboot_timeout: 3600

    - name: Dismount ISO
      win_shell: |
        Dismount-DiskImage -ImagePath "C:\OS\Win11_25H2_English_x64.iso"
      ignore_errors: yes
