---
- name: In-place upgrade Windows 11 21H2 → 25H2
  hosts: all
  gather_facts: no
  tasks:

    - name: Ensure temp directory exists
      win_file:
        path: C:\Temp
        state: directory

    - name: Check if ISO exists
      win_shell: Test-Path "C:\OS\Win11_25H2_English_x64.iso"
      register: iso_exists
      failed_when: iso_exists.stdout | trim != "True"

    - name: Mount local ISO
      win_shell: |
        $iso = "C:\OS\Win11_25H2_English_x64.iso"
        Mount-DiskImage -ImagePath $iso

    - name: Get mounted ISO drive letter
      win_shell: |
        (Get-DiskImage -ImagePath "C:\OS\Win11_25H2_English_x64.iso" | Get-Volume).DriveLetter
      register: iso_drive

    - name: Start Windows 11 setup silently and let it reboot
      win_shell: |
        Start-Process -FilePath "{{ iso_drive.stdout | trim }}:\setup.exe" -ArgumentList "/auto upgrade /quiet /compat IgnoreWarning" -Wait

    - name: Optional: Wait 10 minutes for upgrade to complete
      pause:
        minutes: 10

    - name: Dismount ISO after upgrade (optional)
      win_shell: |
        Dismount-DiskImage -ImagePath "C:\OS\Win11_25H2_English_x64.iso"
      ignore_errors: yes
